### ISSUE TITLE
fails to install on zenoss 4.2.5

### ISSUE THREAD

**Issue by mestia** [NWNCorp/ZenPacks.community.CiscoEnvmonE#3]
That's what I get when I clone the respoistory and try to install:

zenpack --install ZenPacks.community.CiscoEnvMonE
2015-01-09 09:56:26,369 INFO zen.ZPLoader: Loading /usr/local/zenoss/ZenPacks/ZenPacks.community.CiscoEnvMonE-2.0.3-py2.7.egg/ZenPacks/community/CiscoEnvMonE/objects/objects.xml
2015-01-09 09:56:26,370 WARNING zen.AddToPack: Unable to find context path /zport/dmd/Devices/Network/Cisco/rrdTemplates (line 4 ?) for CiscoEnvMonFan
2015-01-09 09:56:26,371 WARNING zen.AddToPack: Not committing any changes
2015-01-09 09:56:26,371 ERROR zen.ZenPackCMD: Error installing ZenPack ZenPacks.community.CiscoEnvMonE
Traceback (most recent call last):
  File "/usr/local/zenoss/Products/ZenUtils/ZenPackCmd.py", line 247, in InstallEggAndZenPack
    fromUI=fromUI)
  File "/usr/local/zenoss/Products/ZenUtils/ZenPackCmd.py", line 477, in InstallDistAsZenPack
    zenPack, deferFileDeletion, existing = transactional_actions()
  File "/usr/local/zenoss/lib/python/ZODB/transact.py", line 44, in g
    r = f(*args, **kwargs)
  File "/usr/local/zenoss/Products/ZenUtils/ZenPackCmd.py", line 436, in transactional_actions
    zenPack.install(dmd)
  File "/usr/local/zenoss/ZenPacks/ZenPacks.community.CiscoEnvMonE-2.0.3-py2.7.egg/ZenPacks/community/CiscoEnvMonE/__init__.py", line 71, in install
    ZenPackBase.install(self, app)
  File "/usr/local/zenoss/Products/ZenModel/ZenPack.py", line 240, in install
    loader.load(self, app)
  File "/usr/local/zenoss/Products/ZenModel/ZenPackLoader.py", line 106, in load
    importer.loadObjectFromXML(xmlfile=f)
  File "/usr/local/zenoss/Products/ZenRelations/ImportRM.py", line 481, in loadObjectFromXML
    parser.parse(self.infile)
  File "/usr/local/zenoss/lib/python/_xmlplus/sax/expatreader.py", line 109, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/zenoss/lib/python/_xmlplus/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/zenoss/lib/python/_xmlplus/sax/expatreader.py", line 216, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/local/zenoss/lib/python/_xmlplus/sax/expatreader.py", line 312, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/local/zenoss/Products/ZenRelations/ImportRM.py", line 161, in startElement
    'attributes:\n%s' % formattedAttrs)
Exception: Unable to create object using the following attributes:
  * id: /zport/dmd/Devices/Network/Cisco/rrdTemplates/CiscoEnvMonFan
  * module: Products.ZenModel.RRDTemplate
  * class: RRDTemplate

2015-01-09 09:56:26,380 ERROR zen.ZenPackCmd: zenpack command failed
Traceback (most recent call last):
  File "/usr/local/zenoss/Products/ZenUtils/zenpack.py", line 487, in <module>
    zp.run()
  File "/usr/local/zenoss/Products/ZenUtils/zenpack.py", line 164, in run
    fromUI=self.options.fromui)
  File "/usr/local/zenoss/Products/ZenUtils/ZenPackCmd.py", line 263, in InstallEggAndZenPack
    raise e
Exception: Unable to create object using the following attributes:
  * id: /zport/dmd/Devices/Network/Cisco/rrdTemplates/CiscoEnvMonFan
  * module: Products.ZenModel.RRDTemplate
  * class: RRDTemplate

**Comment by dougsyer** [comment]
quick question. do you have this device class ?

/Network/Cisco/

in your current zenoss setup?  if not id try to create it then try again..then you can move the templates wherever you want.

if you do have it, i'll have to check the objects.xml to make sure nothing is wrong with it

**Comment by dougsyer** [comment]
oh also...i think i left an egg in the repo that can be used for install.  I almost never install via the gui and i know there can be some issues.

if you have the egg you can ssh to the server, su - zenoss then zenpack --install {path to egg file}

ive never tried to install the source code with a regular install command.  when I install it in development mode i clone the repo then zenpack --link --install {path to zenpack} 

I try to do regular installs in my production and not dev installs usually so I know the code gets over-written entirely when I update the zenpack ..

**Comment by dougsyer** [comment]
oh for some reason i didnt include an .egg file.  I though that zenoss would auto create the egg maybe not..

**Comment by dougsyer** [comment]
i updated this zenpack to fix a few bugs an included the gg in the dist directory.

**Comment by mestia** [comment]
Sorry for not answering so logn.
After I created /Network/Cisco/ device class manually I could successfully install the latest(2.0.5) egg file. Probably you should mention that in the documentation.
Thank you.

**Comment by dougsyer** [comment]
ooh yeah thanks for the feedback.  i hesitate to over-write event classes.  i'll update tha tnow.
